### ISSUE TITLE
Plugin not working in QGIS 3.22 and newer

### ISSUE THREAD

**Issue by ivan-majic** [Awapic/IC#6]
There has been a report that the plugin is not working in QGIS 3.24.2 (Thanks Rachid for reporting!)  and I have seen the same issue in other newer versions of QGIS. The plugin can be set up and started but it would not produce any results.
I have tested the plugin on my Ubuntu machine and QGIS 3.22.4 and found an exception in the following line:
https://github.com/Awapic/IC/blob/ccc989f75687f0a84856f467220d19d3dbbec803/icworker.py#L433
The exception is raised due to too many arguments in the buffer function and due to the third argument being an unexcepted format (integer).
I have looked at the QGIS API documentation for this buffer function ([link](https://api.qgis.org/api/classQgsGeometry.html#adc92a0f2e427c6c5fb8523fa6d159cc4)) and I have found that the specification of EndCapStyle argument as an integer is no longer supported since QGIS 3.22 ([link](https://api.qgis.org/api/classQgis.html#aadaa55e0ec87eb390b18e86ce6a2e8ae)).

**Comment by ivan-majic** [comment]
Fixed in the latest version IC 2.0.2.
#7
